// Generated by convert_prtool_configs_to_3dblox.py

module muyan (
  pin_jtag_trstn,
  pin_jtag_tdo,
  pin_jtag_tdi,
  pin_jtag_tck,
  pin_jtag_tms,
  pin_rd0,
  pin_s_rx_vld,
  pin_s_rx_flit_b0,
  pin_s_rx_flit_b1,
  pin_s_rx_flit_b2,
  pin_s_rx_flit_b3,
  pin_s_rx_flit_b4,
  pin_s_rx_flit_b5,
  pin_rd1,
  pin_s_rx_rplyPkgID,
  pin_s_rx_flit_b6,
  pin_s_rx_flit_b7,
  pin_s_rx_flit_b8,
  pin_s_rx_clk,
  pin_s_rx_flit_b9,
  pin_s_rx_flit_b10,
  pin_rd2,
  pin_s_rx_crdtRB_free,
  pin_s_rx_flit_b11,
  pin_s_rx_flit_b12,
  pin_s_rx_flit_b13,
  pin_s_rx_flit_b14,
  pin_s_rx_flit_b15,
  pin_rd3,
  pin_s_tx_flit_b0,
  pin_s_tx_flit_b1,
  pin_s_tx_flit_b2,
  pin_s_tx_clk,
  pin_s_tx_flit_b3,
  pin_s_tx_flit_b4,
  pin_rd4,
  pin_s_tx_rplyPkgID,
  pin_s_tx_flit_vld,
  pin_s_tx_flit_b5,
  pin_s_tx_flit_b6,
  pin_s_tx_flit_b7,
  pin_s_tx_crdtARW_free,
  pin_rd5,
  pin_chipID2,
  pin_chipID1,
  pin_chipID0,
  pin_package_status_1,
  pin_package_status_0,
  pin_interrupt_1,
  pin_interrupt_0,
  pin_rd6,
  pin_uart_rxd,
  pin_uart_txd,
  pin_Debug_out_0,
  pin_Debug_out_1,
  pin_Debug_out_2,
  pin_Debug_out_3,
  pin_chipID3,
  pin_rd7,
  pin_Test_mode,
  pin_POR,
  pin_spi_csn,
  pin_spi_mosi,
  pin_spi_sck,
  pin_spi_miso,
  pin_rd8,
  pin_m_tx_flit_vld,
  pin_m_tx_flit_b5,
  pin_m_tx_flit_b4,
  pin_m_tx_flit_b3,
  pin_m_tx_flit_b2,
  pin_m_tx_flit_b1,
  pin_m_tx_flit_b0,
  pin_rd9,
  pin_m_tx_crdtRB_free,
  pin_m_tx_flit_b10,
  pin_m_tx_flit_b9,
  pin_m_tx_clk,
  pin_m_tx_flit_b8,
  pin_m_tx_flit_b7,
  pin_m_tx_flit_b6,
  pin_rd10,
  pin_m_tx_rplyPkgID,
  pin_m_tx_flit_b15,
  pin_m_tx_flit_b14,
  pin_m_tx_flit_b13,
  pin_m_tx_flit_b12,
  pin_m_tx_flit_b11,
  pin_rd11,
  pin_m_rx_flit_vld,
  pin_m_rx_flit_b7,
  pin_m_rx_flit_b6,
  pin_m_rx_flit_b5,
  pin_m_rx_crdtARW_free,
  pin_m_rx_rplyPkgID,
  pin_rd12,
  pin_m_rx_flit_b4,
  pin_m_rx_flit_b3,
  pin_m_rx_clk,
  pin_m_rx_flit_b2,
  pin_m_rx_flit_b1,
  pin_m_rx_flit_b0,
  pin_rd13,
  pin_spi_s_dout_1,
  pin_spi_s_sck_1,
  pin_spi_s_din_1,
  pin_spi_s_csn_1,
  pin_rd14,
  pin_spi_s_dout_2,
  pin_spi_s_sck_2,
  pin_spi_s_din_2,
  pin_spi_s_csn_2
);
  inout pin_jtag_trstn;
  inout pin_jtag_tdo;
  inout pin_jtag_tdi;
  inout pin_jtag_tck;
  inout pin_jtag_tms;
  inout pin_rd0;
  input pin_s_rx_vld;
  input pin_s_rx_flit_b0;
  input pin_s_rx_flit_b1;
  input pin_s_rx_flit_b2;
  input pin_s_rx_flit_b3;
  input pin_s_rx_flit_b4;
  input pin_s_rx_flit_b5;
  inout pin_rd1;
  input pin_s_rx_rplyPkgID;
  input pin_s_rx_flit_b6;
  input pin_s_rx_flit_b7;
  input pin_s_rx_flit_b8;
  input pin_s_rx_clk;
  input pin_s_rx_flit_b9;
  input pin_s_rx_flit_b10;
  inout pin_rd2;
  input pin_s_rx_crdtRB_free;
  input pin_s_rx_flit_b11;
  input pin_s_rx_flit_b12;
  input pin_s_rx_flit_b13;
  input pin_s_rx_flit_b14;
  input pin_s_rx_flit_b15;
  inout pin_rd3;
  output pin_s_tx_flit_b0;
  output pin_s_tx_flit_b1;
  output pin_s_tx_flit_b2;
  output pin_s_tx_clk;
  output pin_s_tx_flit_b3;
  output pin_s_tx_flit_b4;
  inout pin_rd4;
  output pin_s_tx_rplyPkgID;
  output pin_s_tx_flit_vld;
  output pin_s_tx_flit_b5;
  output pin_s_tx_flit_b6;
  output pin_s_tx_flit_b7;
  output pin_s_tx_crdtARW_free;
  inout pin_rd5;
  inout pin_chipID2;
  inout pin_chipID1;
  inout pin_chipID0;
  inout pin_package_status_1;
  inout pin_package_status_0;
  inout pin_interrupt_1;
  inout pin_interrupt_0;
  inout pin_rd6;
  inout pin_uart_rxd;
  inout pin_uart_txd;
  inout pin_Debug_out_0;
  inout pin_Debug_out_1;
  inout pin_Debug_out_2;
  inout pin_Debug_out_3;
  inout pin_chipID3;
  inout pin_rd7;
  inout pin_Test_mode;
  inout pin_POR;
  inout pin_spi_csn;
  inout pin_spi_mosi;
  inout pin_spi_sck;
  inout pin_spi_miso;
  inout pin_rd8;
  output pin_m_tx_flit_vld;
  output pin_m_tx_flit_b5;
  output pin_m_tx_flit_b4;
  output pin_m_tx_flit_b3;
  output pin_m_tx_flit_b2;
  output pin_m_tx_flit_b1;
  output pin_m_tx_flit_b0;
  inout pin_rd9;
  output pin_m_tx_crdtRB_free;
  output pin_m_tx_flit_b10;
  output pin_m_tx_flit_b9;
  output pin_m_tx_clk;
  output pin_m_tx_flit_b8;
  output pin_m_tx_flit_b7;
  output pin_m_tx_flit_b6;
  inout pin_rd10;
  output pin_m_tx_rplyPkgID;
  output pin_m_tx_flit_b15;
  output pin_m_tx_flit_b14;
  output pin_m_tx_flit_b13;
  output pin_m_tx_flit_b12;
  output pin_m_tx_flit_b11;
  inout pin_rd11;
  input pin_m_rx_flit_vld;
  input pin_m_rx_flit_b7;
  input pin_m_rx_flit_b6;
  input pin_m_rx_flit_b5;
  input pin_m_rx_crdtARW_free;
  input pin_m_rx_rplyPkgID;
  inout pin_rd12;
  input pin_m_rx_flit_b4;
  input pin_m_rx_flit_b3;
  input pin_m_rx_clk;
  input pin_m_rx_flit_b2;
  input pin_m_rx_flit_b1;
  input pin_m_rx_flit_b0;
  inout pin_rd13;
  inout pin_spi_s_dout_1;
  inout pin_spi_s_sck_1;
  inout pin_spi_s_din_1;
  inout pin_spi_s_csn_1;
  inout pin_rd14;
  inout pin_spi_s_dout_2;
  inout pin_spi_s_sck_2;
  inout pin_spi_s_din_2;
  inout pin_spi_s_csn_2;
endmodule

module PRTOOL_INTERPOSER (
  xinzhai_spi_s_sck_1,
  xinzhai_spi_s_csn_1,
  xinzhai_spi_s_dout_1,
  xinzhai_spi_s_din_1,
  xinzhai_spi_miso,
  xinzhai_spi_csn,
  xinzhai_spi_sck,
  xinzhai_spi_mosi,
  xinzhai_jtag_trstn,
  xinzhai_jtag_tdi,
  xinzhai_jtag_tck,
  xinzhai_jtag_tms,
  xinzhai_uart_txd,
  xinzhai_jtag_tdo,
  xinzhai_uart_rxd,
  xinzhai_spi_s_sck_2,
  xinzhai_spi_s_csn_2,
  xinzhai_spi_s_dout_2,
  xinzhai_spi_s_din_2,
  xinzhai_muyan_0_interrupt_0,
  xinzhai_muyan_1_interrupt_0,
  xinzhai_muyan_6_interrupt_0,
  xinzhai_muyan_7_interrupt_0,
  xinzhai_muyan_0_interrupt_1,
  xinzhai_muyan_1_interrupt_1,
  xinzhai_muyan_6_interrupt_1,
  xinzhai_muyan_7_interrupt_1,
  xinzhai_muyan_2_interrupt_0,
  xinzhai_muyan_3_interrupt_0,
  xinzhai_muyan_4_interrupt_0,
  xinzhai_muyan_5_interrupt_0,
  xinzhai_muyan_2_interrupt_1,
  xinzhai_muyan_3_interrupt_1,
  xinzhai_muyan_4_interrupt_1,
  xinzhai_muyan_5_interrupt_1,
  xinzhai_muyan_8_interrupt_0,
  xinzhai_muyan_9_interrupt_0,
  xinzhai_muyan_14_interrupt_0,
  xinzhai_muyan_15_interrupt_0,
  xinzhai_muyan_8_interrupt_1,
  xinzhai_muyan_9_interrupt_1,
  xinzhai_muyan_14_interrupt_1,
  xinzhai_muyan_15_interrupt_1,
  xinzhai_muyan_10_interrupt_0,
  xinzhai_muyan_11_interrupt_0,
  xinzhai_muyan_12_interrupt_0,
  xinzhai_muyan_13_interrupt_0,
  xinzhai_muyan_10_interrupt_1,
  xinzhai_muyan_11_interrupt_1,
  xinzhai_muyan_12_interrupt_1,
  xinzhai_muyan_13_interrupt_1,
  xinzhai_muyan_0_Test_mode,
  xinzhai_muyan_1_Test_mode,
  xinzhai_muyan_2_Test_mode,
  xinzhai_muyan_3_Test_mode,
  xinzhai_muyan_4_Test_mode,
  xinzhai_muyan_5_Test_mode,
  xinzhai_muyan_6_Test_mode,
  xinzhai_muyan_7_Test_mode,
  xinzhai_muyan_8_Test_mode,
  xinzhai_muyan_9_Test_mode,
  xinzhai_muyan_10_Test_mode,
  xinzhai_muyan_11_Test_mode,
  xinzhai_muyan_12_Test_mode,
  xinzhai_muyan_13_Test_mode,
  xinzhai_muyan_14_Test_mode,
  xinzhai_muyan_15_Test_mode,
  xinzhai_muyan_0_POR,
  xinzhai_muyan_1_POR,
  xinzhai_muyan_2_POR,
  xinzhai_muyan_3_POR,
  xinzhai_muyan_4_POR,
  xinzhai_muyan_5_POR,
  xinzhai_muyan_6_POR,
  xinzhai_muyan_7_POR,
  xinzhai_muyan_8_POR,
  xinzhai_muyan_9_POR,
  xinzhai_muyan_10_POR,
  xinzhai_muyan_11_POR,
  xinzhai_muyan_12_POR,
  xinzhai_muyan_13_POR,
  xinzhai_muyan_14_POR,
  xinzhai_muyan_15_POR
);
  inout xinzhai_spi_s_sck_1;
  inout xinzhai_spi_s_csn_1;
  inout xinzhai_spi_s_dout_1;
  inout xinzhai_spi_s_din_1;
  inout xinzhai_spi_miso;
  inout xinzhai_spi_csn;
  inout xinzhai_spi_sck;
  inout xinzhai_spi_mosi;
  inout xinzhai_jtag_trstn;
  inout xinzhai_jtag_tdi;
  inout xinzhai_jtag_tck;
  inout xinzhai_jtag_tms;
  inout xinzhai_uart_txd;
  input xinzhai_jtag_tdo;
  inout xinzhai_uart_rxd;
  inout xinzhai_spi_s_sck_2;
  inout xinzhai_spi_s_csn_2;
  inout xinzhai_spi_s_dout_2;
  inout xinzhai_spi_s_din_2;
  inout xinzhai_muyan_0_interrupt_0;
  inout xinzhai_muyan_1_interrupt_0;
  inout xinzhai_muyan_6_interrupt_0;
  inout xinzhai_muyan_7_interrupt_0;
  inout xinzhai_muyan_0_interrupt_1;
  inout xinzhai_muyan_1_interrupt_1;
  inout xinzhai_muyan_6_interrupt_1;
  inout xinzhai_muyan_7_interrupt_1;
  inout xinzhai_muyan_2_interrupt_0;
  inout xinzhai_muyan_3_interrupt_0;
  inout xinzhai_muyan_4_interrupt_0;
  inout xinzhai_muyan_5_interrupt_0;
  inout xinzhai_muyan_2_interrupt_1;
  inout xinzhai_muyan_3_interrupt_1;
  inout xinzhai_muyan_4_interrupt_1;
  inout xinzhai_muyan_5_interrupt_1;
  inout xinzhai_muyan_8_interrupt_0;
  inout xinzhai_muyan_9_interrupt_0;
  inout xinzhai_muyan_14_interrupt_0;
  inout xinzhai_muyan_15_interrupt_0;
  inout xinzhai_muyan_8_interrupt_1;
  inout xinzhai_muyan_9_interrupt_1;
  inout xinzhai_muyan_14_interrupt_1;
  inout xinzhai_muyan_15_interrupt_1;
  inout xinzhai_muyan_10_interrupt_0;
  inout xinzhai_muyan_11_interrupt_0;
  inout xinzhai_muyan_12_interrupt_0;
  inout xinzhai_muyan_13_interrupt_0;
  inout xinzhai_muyan_10_interrupt_1;
  inout xinzhai_muyan_11_interrupt_1;
  inout xinzhai_muyan_12_interrupt_1;
  inout xinzhai_muyan_13_interrupt_1;
  inout xinzhai_muyan_0_Test_mode;
  inout xinzhai_muyan_1_Test_mode;
  inout xinzhai_muyan_2_Test_mode;
  inout xinzhai_muyan_3_Test_mode;
  inout xinzhai_muyan_4_Test_mode;
  inout xinzhai_muyan_5_Test_mode;
  inout xinzhai_muyan_6_Test_mode;
  inout xinzhai_muyan_7_Test_mode;
  inout xinzhai_muyan_8_Test_mode;
  inout xinzhai_muyan_9_Test_mode;
  inout xinzhai_muyan_10_Test_mode;
  inout xinzhai_muyan_11_Test_mode;
  inout xinzhai_muyan_12_Test_mode;
  inout xinzhai_muyan_13_Test_mode;
  inout xinzhai_muyan_14_Test_mode;
  inout xinzhai_muyan_15_Test_mode;
  inout xinzhai_muyan_0_POR;
  inout xinzhai_muyan_1_POR;
  inout xinzhai_muyan_2_POR;
  inout xinzhai_muyan_3_POR;
  inout xinzhai_muyan_4_POR;
  inout xinzhai_muyan_5_POR;
  inout xinzhai_muyan_6_POR;
  inout xinzhai_muyan_7_POR;
  inout xinzhai_muyan_8_POR;
  inout xinzhai_muyan_9_POR;
  inout xinzhai_muyan_10_POR;
  inout xinzhai_muyan_11_POR;
  inout xinzhai_muyan_12_POR;
  inout xinzhai_muyan_13_POR;
  inout xinzhai_muyan_14_POR;
  inout xinzhai_muyan_15_POR;
endmodule

module case2_3dblox;
  wire [11:0] prsync__m0__g1;
  wire [19:0] prsync__m0__g2;
  wire [11:0] prsync__m0__g3;
  wire [19:0] prsync__m0__g4;
  wire prunconnected__p0;
  wire prunconnected__p1;
  wire prunconnected__p10;
  wire prunconnected__p11;
  wire prunconnected__p12;
  wire prunconnected__p13;
  wire prunconnected__p14;
  wire prunconnected__p15;
  wire prunconnected__p16;
  wire prunconnected__p17;
  wire prunconnected__p18;
  wire prunconnected__p19;
  wire prunconnected__p20;
  wire prunconnected__p21;
  wire prunconnected__p22;
  wire prunconnected__p23;
  wire prunconnected__p24;
  wire prunconnected__p25;
  wire prunconnected__p26;
  wire prunconnected__p27;
  wire prunconnected__p28;
  wire prunconnected__p29;
  wire prunconnected__p3;
  wire prunconnected__p30;
  wire prunconnected__p31;
  wire prunconnected__p32;
  wire prunconnected__p33;
  wire prunconnected__p34;
  wire prunconnected__p35;
  wire prunconnected__p36;
  wire prunconnected__p37;
  wire prunconnected__p38;
  wire prunconnected__p39;
  wire prunconnected__p4;
  wire prunconnected__p40;
  wire prunconnected__p41;
  wire prunconnected__p42;
  wire prunconnected__p43;
  wire prunconnected__p44;
  wire prunconnected__p45;
  wire prunconnected__p46;
  wire prunconnected__p47;
  wire prunconnected__p48;
  wire prunconnected__p49;
  wire prunconnected__p5;
  wire prunconnected__p50;
  wire prunconnected__p51;
  wire prunconnected__p52;
  wire prunconnected__p53;
  wire prunconnected__p54;
  wire prunconnected__p55;
  wire prunconnected__p56;
  wire prunconnected__p57;
  wire prunconnected__p58;
  wire prunconnected__p59;
  wire prunconnected__p6;
  wire prunconnected__p60;
  wire prunconnected__p61;
  wire prunconnected__p62;
  wire prunconnected__p63;
  wire prunconnected__p64;
  wire prunconnected__p65;
  wire prunconnected__p66;
  wire prunconnected__p67;
  wire prunconnected__p68;
  wire prunconnected__p69;
  wire prunconnected__p7;
  wire prunconnected__p70;
  wire prunconnected__p71;
  wire prunconnected__p72;
  wire prunconnected__p73;
  wire prunconnected__p74;
  wire prunconnected__p75;
  wire prunconnected__p76;
  wire prunconnected__p77;
  wire prunconnected__p78;
  wire prunconnected__p79;
  wire prunconnected__p8;
  wire prunconnected__p80;
  wire prunconnected__p81;
  wire prunconnected__p82;
  wire prunconnected__p9;
  // PRTOOL_DIRECTION muyan_0.pin_m_rx_clk input
  // PRTOOL_DIRECTION muyan_0.pin_m_rx_crdtARW_free input
  // PRTOOL_DIRECTION muyan_0.pin_m_rx_flit_b0 input
  // PRTOOL_DIRECTION muyan_0.pin_m_rx_flit_b1 input
  // PRTOOL_DIRECTION muyan_0.pin_m_rx_flit_b2 input
  // PRTOOL_DIRECTION muyan_0.pin_m_rx_flit_b3 input
  // PRTOOL_DIRECTION muyan_0.pin_m_rx_flit_b4 input
  // PRTOOL_DIRECTION muyan_0.pin_m_rx_flit_b5 input
  // PRTOOL_DIRECTION muyan_0.pin_m_rx_flit_b6 input
  // PRTOOL_DIRECTION muyan_0.pin_m_rx_flit_b7 input
  // PRTOOL_DIRECTION muyan_0.pin_m_rx_flit_vld input
  // PRTOOL_DIRECTION muyan_0.pin_m_rx_rplyPkgID input
  // PRTOOL_DIRECTION muyan_0.pin_m_tx_clk output
  // PRTOOL_DIRECTION muyan_0.pin_m_tx_crdtRB_free output
  // PRTOOL_DIRECTION muyan_0.pin_m_tx_flit_b0 output
  // PRTOOL_DIRECTION muyan_0.pin_m_tx_flit_b1 output
  // PRTOOL_DIRECTION muyan_0.pin_m_tx_flit_b10 output
  // PRTOOL_DIRECTION muyan_0.pin_m_tx_flit_b11 output
  // PRTOOL_DIRECTION muyan_0.pin_m_tx_flit_b12 output
  // PRTOOL_DIRECTION muyan_0.pin_m_tx_flit_b13 output
  // PRTOOL_DIRECTION muyan_0.pin_m_tx_flit_b14 output
  // PRTOOL_DIRECTION muyan_0.pin_m_tx_flit_b15 output
  // PRTOOL_DIRECTION muyan_0.pin_m_tx_flit_b2 output
  // PRTOOL_DIRECTION muyan_0.pin_m_tx_flit_b3 output
  // PRTOOL_DIRECTION muyan_0.pin_m_tx_flit_b4 output
  // PRTOOL_DIRECTION muyan_0.pin_m_tx_flit_b5 output
  // PRTOOL_DIRECTION muyan_0.pin_m_tx_flit_b6 output
  // PRTOOL_DIRECTION muyan_0.pin_m_tx_flit_b7 output
  // PRTOOL_DIRECTION muyan_0.pin_m_tx_flit_b8 output
  // PRTOOL_DIRECTION muyan_0.pin_m_tx_flit_b9 output
  // PRTOOL_DIRECTION muyan_0.pin_m_tx_flit_vld output
  // PRTOOL_DIRECTION muyan_0.pin_m_tx_rplyPkgID output
  // PRTOOL_DIRECTION muyan_0.pin_s_rx_clk input
  // PRTOOL_DIRECTION muyan_0.pin_s_rx_crdtRB_free input
  // PRTOOL_DIRECTION muyan_0.pin_s_rx_flit_b0 input
  // PRTOOL_DIRECTION muyan_0.pin_s_rx_flit_b1 input
  // PRTOOL_DIRECTION muyan_0.pin_s_rx_flit_b10 input
  // PRTOOL_DIRECTION muyan_0.pin_s_rx_flit_b11 input
  // PRTOOL_DIRECTION muyan_0.pin_s_rx_flit_b12 input
  // PRTOOL_DIRECTION muyan_0.pin_s_rx_flit_b13 input
  // PRTOOL_DIRECTION muyan_0.pin_s_rx_flit_b14 input
  // PRTOOL_DIRECTION muyan_0.pin_s_rx_flit_b15 input
  // PRTOOL_DIRECTION muyan_0.pin_s_rx_flit_b2 input
  // PRTOOL_DIRECTION muyan_0.pin_s_rx_flit_b3 input
  // PRTOOL_DIRECTION muyan_0.pin_s_rx_flit_b4 input
  // PRTOOL_DIRECTION muyan_0.pin_s_rx_flit_b5 input
  // PRTOOL_DIRECTION muyan_0.pin_s_rx_flit_b6 input
  // PRTOOL_DIRECTION muyan_0.pin_s_rx_flit_b7 input
  // PRTOOL_DIRECTION muyan_0.pin_s_rx_flit_b8 input
  // PRTOOL_DIRECTION muyan_0.pin_s_rx_flit_b9 input
  // PRTOOL_DIRECTION muyan_0.pin_s_rx_rplyPkgID input
  // PRTOOL_DIRECTION muyan_0.pin_s_rx_vld input
  // PRTOOL_DIRECTION muyan_0.pin_s_tx_clk output
  // PRTOOL_DIRECTION muyan_0.pin_s_tx_crdtARW_free output
  // PRTOOL_DIRECTION muyan_0.pin_s_tx_flit_b0 output
  // PRTOOL_DIRECTION muyan_0.pin_s_tx_flit_b1 output
  // PRTOOL_DIRECTION muyan_0.pin_s_tx_flit_b2 output
  // PRTOOL_DIRECTION muyan_0.pin_s_tx_flit_b3 output
  // PRTOOL_DIRECTION muyan_0.pin_s_tx_flit_b4 output
  // PRTOOL_DIRECTION muyan_0.pin_s_tx_flit_b5 output
  // PRTOOL_DIRECTION muyan_0.pin_s_tx_flit_b6 output
  // PRTOOL_DIRECTION muyan_0.pin_s_tx_flit_b7 output
  // PRTOOL_DIRECTION muyan_0.pin_s_tx_flit_vld output
  // PRTOOL_DIRECTION muyan_0.pin_s_tx_rplyPkgID output
  // PRTOOL_DIRECTION muyan_1.pin_m_rx_clk input
  // PRTOOL_DIRECTION muyan_1.pin_m_rx_crdtARW_free input
  // PRTOOL_DIRECTION muyan_1.pin_m_rx_flit_b0 input
  // PRTOOL_DIRECTION muyan_1.pin_m_rx_flit_b1 input
  // PRTOOL_DIRECTION muyan_1.pin_m_rx_flit_b2 input
  // PRTOOL_DIRECTION muyan_1.pin_m_rx_flit_b3 input
  // PRTOOL_DIRECTION muyan_1.pin_m_rx_flit_b4 input
  // PRTOOL_DIRECTION muyan_1.pin_m_rx_flit_b5 input
  // PRTOOL_DIRECTION muyan_1.pin_m_rx_flit_b6 input
  // PRTOOL_DIRECTION muyan_1.pin_m_rx_flit_b7 input
  // PRTOOL_DIRECTION muyan_1.pin_m_rx_flit_vld input
  // PRTOOL_DIRECTION muyan_1.pin_m_rx_rplyPkgID input
  // PRTOOL_DIRECTION muyan_1.pin_m_tx_clk output
  // PRTOOL_DIRECTION muyan_1.pin_m_tx_crdtRB_free output
  // PRTOOL_DIRECTION muyan_1.pin_m_tx_flit_b0 output
  // PRTOOL_DIRECTION muyan_1.pin_m_tx_flit_b1 output
  // PRTOOL_DIRECTION muyan_1.pin_m_tx_flit_b10 output
  // PRTOOL_DIRECTION muyan_1.pin_m_tx_flit_b11 output
  // PRTOOL_DIRECTION muyan_1.pin_m_tx_flit_b12 output
  // PRTOOL_DIRECTION muyan_1.pin_m_tx_flit_b13 output
  // PRTOOL_DIRECTION muyan_1.pin_m_tx_flit_b14 output
  // PRTOOL_DIRECTION muyan_1.pin_m_tx_flit_b15 output
  // PRTOOL_DIRECTION muyan_1.pin_m_tx_flit_b2 output
  // PRTOOL_DIRECTION muyan_1.pin_m_tx_flit_b3 output
  // PRTOOL_DIRECTION muyan_1.pin_m_tx_flit_b4 output
  // PRTOOL_DIRECTION muyan_1.pin_m_tx_flit_b5 output
  // PRTOOL_DIRECTION muyan_1.pin_m_tx_flit_b6 output
  // PRTOOL_DIRECTION muyan_1.pin_m_tx_flit_b7 output
  // PRTOOL_DIRECTION muyan_1.pin_m_tx_flit_b8 output
  // PRTOOL_DIRECTION muyan_1.pin_m_tx_flit_b9 output
  // PRTOOL_DIRECTION muyan_1.pin_m_tx_flit_vld output
  // PRTOOL_DIRECTION muyan_1.pin_m_tx_rplyPkgID output
  // PRTOOL_DIRECTION muyan_1.pin_s_rx_clk input
  // PRTOOL_DIRECTION muyan_1.pin_s_rx_crdtRB_free input
  // PRTOOL_DIRECTION muyan_1.pin_s_rx_flit_b0 input
  // PRTOOL_DIRECTION muyan_1.pin_s_rx_flit_b1 input
  // PRTOOL_DIRECTION muyan_1.pin_s_rx_flit_b10 input
  // PRTOOL_DIRECTION muyan_1.pin_s_rx_flit_b11 input
  // PRTOOL_DIRECTION muyan_1.pin_s_rx_flit_b12 input
  // PRTOOL_DIRECTION muyan_1.pin_s_rx_flit_b13 input
  // PRTOOL_DIRECTION muyan_1.pin_s_rx_flit_b14 input
  // PRTOOL_DIRECTION muyan_1.pin_s_rx_flit_b15 input
  // PRTOOL_DIRECTION muyan_1.pin_s_rx_flit_b2 input
  // PRTOOL_DIRECTION muyan_1.pin_s_rx_flit_b3 input
  // PRTOOL_DIRECTION muyan_1.pin_s_rx_flit_b4 input
  // PRTOOL_DIRECTION muyan_1.pin_s_rx_flit_b5 input
  // PRTOOL_DIRECTION muyan_1.pin_s_rx_flit_b6 input
  // PRTOOL_DIRECTION muyan_1.pin_s_rx_flit_b7 input
  // PRTOOL_DIRECTION muyan_1.pin_s_rx_flit_b8 input
  // PRTOOL_DIRECTION muyan_1.pin_s_rx_flit_b9 input
  // PRTOOL_DIRECTION muyan_1.pin_s_rx_rplyPkgID input
  // PRTOOL_DIRECTION muyan_1.pin_s_rx_vld input
  // PRTOOL_DIRECTION muyan_1.pin_s_tx_clk output
  // PRTOOL_DIRECTION muyan_1.pin_s_tx_crdtARW_free output
  // PRTOOL_DIRECTION muyan_1.pin_s_tx_flit_b0 output
  // PRTOOL_DIRECTION muyan_1.pin_s_tx_flit_b1 output
  // PRTOOL_DIRECTION muyan_1.pin_s_tx_flit_b2 output
  // PRTOOL_DIRECTION muyan_1.pin_s_tx_flit_b3 output
  // PRTOOL_DIRECTION muyan_1.pin_s_tx_flit_b4 output
  // PRTOOL_DIRECTION muyan_1.pin_s_tx_flit_b5 output
  // PRTOOL_DIRECTION muyan_1.pin_s_tx_flit_b6 output
  // PRTOOL_DIRECTION muyan_1.pin_s_tx_flit_b7 output
  // PRTOOL_DIRECTION muyan_1.pin_s_tx_flit_vld output
  // PRTOOL_DIRECTION muyan_1.pin_s_tx_rplyPkgID output
  // PRTOOL_DIRECTION prtool_interposer.xinzhai_jtag_tdo input
  // PRTOOL_CONNECTION prtool__m0__g1 muyan_1.pin_s_tx_flit_b0 muyan_0.pin_m_rx_flit_b0
  // PRTOOL_CONNECTION prtool__m0__g1 muyan_1.pin_s_tx_flit_b1 muyan_0.pin_m_rx_flit_b1
  // PRTOOL_CONNECTION prtool__m0__g1 muyan_1.pin_s_tx_flit_b2 muyan_0.pin_m_rx_flit_b2
  // PRTOOL_CONNECTION prtool__m0__g1 muyan_1.pin_s_tx_flit_b3 muyan_0.pin_m_rx_flit_b3
  // PRTOOL_CONNECTION prtool__m0__g1 muyan_1.pin_s_tx_flit_b4 muyan_0.pin_m_rx_flit_b4
  // PRTOOL_CONNECTION prtool__m0__g1 muyan_1.pin_s_tx_flit_b5 muyan_0.pin_m_rx_flit_b5
  // PRTOOL_CONNECTION prtool__m0__g1 muyan_1.pin_s_tx_flit_b6 muyan_0.pin_m_rx_flit_b6
  // PRTOOL_CONNECTION prtool__m0__g1 muyan_1.pin_s_tx_flit_b7 muyan_0.pin_m_rx_flit_b7
  // PRTOOL_CONNECTION prtool__m0__g1 muyan_1.pin_s_tx_rplyPkgID muyan_0.pin_m_rx_rplyPkgID
  // PRTOOL_CONNECTION prtool__m0__g1 muyan_1.pin_s_tx_crdtARW_free muyan_0.pin_m_rx_crdtARW_free
  // PRTOOL_CONNECTION prtool__m0__g1 muyan_1.pin_s_tx_clk muyan_0.pin_m_rx_clk
  // PRTOOL_CONNECTION prtool__m0__g1 muyan_1.pin_s_tx_flit_vld muyan_0.pin_m_rx_flit_vld
  // PRTOOL_CONNECTION prtool__m0__g2 muyan_0.pin_m_tx_flit_b0 muyan_1.pin_s_rx_flit_b0
  // PRTOOL_CONNECTION prtool__m0__g2 muyan_0.pin_m_tx_flit_b1 muyan_1.pin_s_rx_flit_b1
  // PRTOOL_CONNECTION prtool__m0__g2 muyan_0.pin_m_tx_flit_b2 muyan_1.pin_s_rx_flit_b2
  // PRTOOL_CONNECTION prtool__m0__g2 muyan_0.pin_m_tx_flit_b3 muyan_1.pin_s_rx_flit_b3
  // PRTOOL_CONNECTION prtool__m0__g2 muyan_0.pin_m_tx_flit_b4 muyan_1.pin_s_rx_flit_b4
  // PRTOOL_CONNECTION prtool__m0__g2 muyan_0.pin_m_tx_flit_b5 muyan_1.pin_s_rx_flit_b5
  // PRTOOL_CONNECTION prtool__m0__g2 muyan_0.pin_m_tx_flit_b6 muyan_1.pin_s_rx_flit_b6
  // PRTOOL_CONNECTION prtool__m0__g2 muyan_0.pin_m_tx_flit_b7 muyan_1.pin_s_rx_flit_b7
  // PRTOOL_CONNECTION prtool__m0__g2 muyan_0.pin_m_tx_flit_b8 muyan_1.pin_s_rx_flit_b8
  // PRTOOL_CONNECTION prtool__m0__g2 muyan_0.pin_m_tx_flit_b9 muyan_1.pin_s_rx_flit_b9
  // PRTOOL_CONNECTION prtool__m0__g2 muyan_0.pin_m_tx_flit_b10 muyan_1.pin_s_rx_flit_b10
  // PRTOOL_CONNECTION prtool__m0__g2 muyan_0.pin_m_tx_flit_b11 muyan_1.pin_s_rx_flit_b11
  // PRTOOL_CONNECTION prtool__m0__g2 muyan_0.pin_m_tx_flit_b12 muyan_1.pin_s_rx_flit_b12
  // PRTOOL_CONNECTION prtool__m0__g2 muyan_0.pin_m_tx_flit_b13 muyan_1.pin_s_rx_flit_b13
  // PRTOOL_CONNECTION prtool__m0__g2 muyan_0.pin_m_tx_flit_b14 muyan_1.pin_s_rx_flit_b14
  // PRTOOL_CONNECTION prtool__m0__g2 muyan_0.pin_m_tx_flit_b15 muyan_1.pin_s_rx_flit_b15
  // PRTOOL_CONNECTION prtool__m0__g2 muyan_0.pin_m_tx_rplyPkgID muyan_1.pin_s_rx_rplyPkgID
  // PRTOOL_CONNECTION prtool__m0__g2 muyan_0.pin_m_tx_crdtRB_free muyan_1.pin_s_rx_crdtRB_free
  // PRTOOL_CONNECTION prtool__m0__g2 muyan_0.pin_m_tx_clk muyan_1.pin_s_rx_clk
  // PRTOOL_CONNECTION prtool__m0__g2 muyan_0.pin_m_tx_flit_vld muyan_1.pin_s_rx_vld
  // PRTOOL_CONNECTION prtool__m0__g3 muyan_0.pin_s_tx_flit_b0 muyan_1.pin_m_rx_flit_b0
  // PRTOOL_CONNECTION prtool__m0__g3 muyan_0.pin_s_tx_flit_b1 muyan_1.pin_m_rx_flit_b1
  // PRTOOL_CONNECTION prtool__m0__g3 muyan_0.pin_s_tx_flit_b2 muyan_1.pin_m_rx_flit_b2
  // PRTOOL_CONNECTION prtool__m0__g3 muyan_0.pin_s_tx_flit_b3 muyan_1.pin_m_rx_flit_b3
  // PRTOOL_CONNECTION prtool__m0__g3 muyan_0.pin_s_tx_flit_b4 muyan_1.pin_m_rx_flit_b4
  // PRTOOL_CONNECTION prtool__m0__g3 muyan_0.pin_s_tx_flit_b5 muyan_1.pin_m_rx_flit_b5
  // PRTOOL_CONNECTION prtool__m0__g3 muyan_0.pin_s_tx_flit_b6 muyan_1.pin_m_rx_flit_b6
  // PRTOOL_CONNECTION prtool__m0__g3 muyan_0.pin_s_tx_flit_b7 muyan_1.pin_m_rx_flit_b7
  // PRTOOL_CONNECTION prtool__m0__g3 muyan_0.pin_s_tx_rplyPkgID muyan_1.pin_m_rx_rplyPkgID
  // PRTOOL_CONNECTION prtool__m0__g3 muyan_0.pin_s_tx_crdtARW_free muyan_1.pin_m_rx_crdtARW_free
  // PRTOOL_CONNECTION prtool__m0__g3 muyan_0.pin_s_tx_clk muyan_1.pin_m_rx_clk
  // PRTOOL_CONNECTION prtool__m0__g3 muyan_0.pin_s_tx_flit_vld muyan_1.pin_m_rx_flit_vld
  // PRTOOL_CONNECTION prtool__m0__g4 muyan_1.pin_m_tx_flit_b0 muyan_0.pin_s_rx_flit_b0
  // PRTOOL_CONNECTION prtool__m0__g4 muyan_1.pin_m_tx_flit_b1 muyan_0.pin_s_rx_flit_b1
  // PRTOOL_CONNECTION prtool__m0__g4 muyan_1.pin_m_tx_flit_b2 muyan_0.pin_s_rx_flit_b2
  // PRTOOL_CONNECTION prtool__m0__g4 muyan_1.pin_m_tx_flit_b3 muyan_0.pin_s_rx_flit_b3
  // PRTOOL_CONNECTION prtool__m0__g4 muyan_1.pin_m_tx_flit_b4 muyan_0.pin_s_rx_flit_b4
  // PRTOOL_CONNECTION prtool__m0__g4 muyan_1.pin_m_tx_flit_b5 muyan_0.pin_s_rx_flit_b5
  // PRTOOL_CONNECTION prtool__m0__g4 muyan_1.pin_m_tx_flit_b6 muyan_0.pin_s_rx_flit_b6
  // PRTOOL_CONNECTION prtool__m0__g4 muyan_1.pin_m_tx_flit_b7 muyan_0.pin_s_rx_flit_b7
  // PRTOOL_CONNECTION prtool__m0__g4 muyan_1.pin_m_tx_flit_b8 muyan_0.pin_s_rx_flit_b8
  // PRTOOL_CONNECTION prtool__m0__g4 muyan_1.pin_m_tx_flit_b9 muyan_0.pin_s_rx_flit_b9
  // PRTOOL_CONNECTION prtool__m0__g4 muyan_1.pin_m_tx_flit_b10 muyan_0.pin_s_rx_flit_b10
  // PRTOOL_CONNECTION prtool__m0__g4 muyan_1.pin_m_tx_flit_b11 muyan_0.pin_s_rx_flit_b11
  // PRTOOL_CONNECTION prtool__m0__g4 muyan_1.pin_m_tx_flit_b12 muyan_0.pin_s_rx_flit_b12
  // PRTOOL_CONNECTION prtool__m0__g4 muyan_1.pin_m_tx_flit_b13 muyan_0.pin_s_rx_flit_b13
  // PRTOOL_CONNECTION prtool__m0__g4 muyan_1.pin_m_tx_flit_b14 muyan_0.pin_s_rx_flit_b14
  // PRTOOL_CONNECTION prtool__m0__g4 muyan_1.pin_m_tx_flit_b15 muyan_0.pin_s_rx_flit_b15
  // PRTOOL_CONNECTION prtool__m0__g4 muyan_1.pin_m_tx_rplyPkgID muyan_0.pin_s_rx_rplyPkgID
  // PRTOOL_CONNECTION prtool__m0__g4 muyan_1.pin_m_tx_crdtRB_free muyan_0.pin_s_rx_crdtRB_free
  // PRTOOL_CONNECTION prtool__m0__g4 muyan_1.pin_m_tx_clk muyan_0.pin_s_rx_clk
  // PRTOOL_CONNECTION prtool__m0__g4 muyan_1.pin_m_tx_flit_vld muyan_0.pin_s_rx_vld
  // PRTOOL_CONNECTION prtool__m0__g-1 muyan_0.pin_m_tx_flit_b0 prtool_interposer.xinzhai_jtag_tdo
  muyan muyan_0 (
    .pin_m_rx_clk(prsync__m0__g1[0]),
    .pin_m_rx_crdtARW_free(prsync__m0__g1[1]),
    .pin_m_rx_flit_b0(prsync__m0__g1[2]),
    .pin_m_rx_flit_b1(prsync__m0__g1[3]),
    .pin_m_rx_flit_b2(prsync__m0__g1[4]),
    .pin_m_rx_flit_b3(prsync__m0__g1[5]),
    .pin_m_rx_flit_b4(prsync__m0__g1[6]),
    .pin_m_rx_flit_b5(prsync__m0__g1[7]),
    .pin_m_rx_flit_b6(prsync__m0__g1[8]),
    .pin_m_rx_flit_b7(prsync__m0__g1[9]),
    .pin_m_rx_flit_vld(prsync__m0__g1[10]),
    .pin_m_rx_rplyPkgID(prsync__m0__g1[11]),
    .pin_m_tx_clk(prsync__m0__g2[0]),
    .pin_m_tx_crdtRB_free(prsync__m0__g2[1]),
    .pin_m_tx_flit_b0(prsync__m0__g2[2]),
    .pin_m_tx_flit_b1(prsync__m0__g2[3]),
    .pin_m_tx_flit_b10(prsync__m0__g2[4]),
    .pin_m_tx_flit_b11(prsync__m0__g2[5]),
    .pin_m_tx_flit_b12(prsync__m0__g2[6]),
    .pin_m_tx_flit_b13(prsync__m0__g2[7]),
    .pin_m_tx_flit_b14(prsync__m0__g2[8]),
    .pin_m_tx_flit_b15(prsync__m0__g2[9]),
    .pin_m_tx_flit_b2(prsync__m0__g2[10]),
    .pin_m_tx_flit_b3(prsync__m0__g2[11]),
    .pin_m_tx_flit_b4(prsync__m0__g2[12]),
    .pin_m_tx_flit_b5(prsync__m0__g2[13]),
    .pin_m_tx_flit_b6(prsync__m0__g2[14]),
    .pin_m_tx_flit_b7(prsync__m0__g2[15]),
    .pin_m_tx_flit_b8(prsync__m0__g2[16]),
    .pin_m_tx_flit_b9(prsync__m0__g2[17]),
    .pin_m_tx_flit_vld(prsync__m0__g2[18]),
    .pin_m_tx_rplyPkgID(prsync__m0__g2[19]),
    .pin_s_rx_clk(prsync__m0__g4[0]),
    .pin_s_rx_crdtRB_free(prsync__m0__g4[1]),
    .pin_s_rx_flit_b0(prsync__m0__g4[2]),
    .pin_s_rx_flit_b1(prsync__m0__g4[3]),
    .pin_s_rx_flit_b10(prsync__m0__g4[4]),
    .pin_s_rx_flit_b11(prsync__m0__g4[5]),
    .pin_s_rx_flit_b12(prsync__m0__g4[6]),
    .pin_s_rx_flit_b13(prsync__m0__g4[7]),
    .pin_s_rx_flit_b14(prsync__m0__g4[8]),
    .pin_s_rx_flit_b15(prsync__m0__g4[9]),
    .pin_s_rx_flit_b2(prsync__m0__g4[10]),
    .pin_s_rx_flit_b3(prsync__m0__g4[11]),
    .pin_s_rx_flit_b4(prsync__m0__g4[12]),
    .pin_s_rx_flit_b5(prsync__m0__g4[13]),
    .pin_s_rx_flit_b6(prsync__m0__g4[14]),
    .pin_s_rx_flit_b7(prsync__m0__g4[15]),
    .pin_s_rx_flit_b8(prsync__m0__g4[16]),
    .pin_s_rx_flit_b9(prsync__m0__g4[17]),
    .pin_s_rx_rplyPkgID(prsync__m0__g4[18]),
    .pin_s_rx_vld(prsync__m0__g4[19]),
    .pin_s_tx_clk(prsync__m0__g3[0]),
    .pin_s_tx_crdtARW_free(prsync__m0__g3[1]),
    .pin_s_tx_flit_b0(prsync__m0__g3[2]),
    .pin_s_tx_flit_b1(prsync__m0__g3[3]),
    .pin_s_tx_flit_b2(prsync__m0__g3[4]),
    .pin_s_tx_flit_b3(prsync__m0__g3[5]),
    .pin_s_tx_flit_b4(prsync__m0__g3[6]),
    .pin_s_tx_flit_b5(prsync__m0__g3[7]),
    .pin_s_tx_flit_b6(prsync__m0__g3[8]),
    .pin_s_tx_flit_b7(prsync__m0__g3[9]),
    .pin_s_tx_flit_vld(prsync__m0__g3[10]),
    .pin_s_tx_rplyPkgID(prsync__m0__g3[11])
  );
  muyan muyan_1 (
    .pin_m_rx_clk(prsync__m0__g3[0]),
    .pin_m_rx_crdtARW_free(prsync__m0__g3[1]),
    .pin_m_rx_flit_b0(prsync__m0__g3[2]),
    .pin_m_rx_flit_b1(prsync__m0__g3[3]),
    .pin_m_rx_flit_b2(prsync__m0__g3[4]),
    .pin_m_rx_flit_b3(prsync__m0__g3[5]),
    .pin_m_rx_flit_b4(prsync__m0__g3[6]),
    .pin_m_rx_flit_b5(prsync__m0__g3[7]),
    .pin_m_rx_flit_b6(prsync__m0__g3[8]),
    .pin_m_rx_flit_b7(prsync__m0__g3[9]),
    .pin_m_rx_flit_vld(prsync__m0__g3[10]),
    .pin_m_rx_rplyPkgID(prsync__m0__g3[11]),
    .pin_m_tx_clk(prsync__m0__g4[0]),
    .pin_m_tx_crdtRB_free(prsync__m0__g4[1]),
    .pin_m_tx_flit_b0(prsync__m0__g4[2]),
    .pin_m_tx_flit_b1(prsync__m0__g4[3]),
    .pin_m_tx_flit_b10(prsync__m0__g4[4]),
    .pin_m_tx_flit_b11(prsync__m0__g4[5]),
    .pin_m_tx_flit_b12(prsync__m0__g4[6]),
    .pin_m_tx_flit_b13(prsync__m0__g4[7]),
    .pin_m_tx_flit_b14(prsync__m0__g4[8]),
    .pin_m_tx_flit_b15(prsync__m0__g4[9]),
    .pin_m_tx_flit_b2(prsync__m0__g4[10]),
    .pin_m_tx_flit_b3(prsync__m0__g4[11]),
    .pin_m_tx_flit_b4(prsync__m0__g4[12]),
    .pin_m_tx_flit_b5(prsync__m0__g4[13]),
    .pin_m_tx_flit_b6(prsync__m0__g4[14]),
    .pin_m_tx_flit_b7(prsync__m0__g4[15]),
    .pin_m_tx_flit_b8(prsync__m0__g4[16]),
    .pin_m_tx_flit_b9(prsync__m0__g4[17]),
    .pin_m_tx_flit_vld(prsync__m0__g4[19]),
    .pin_m_tx_rplyPkgID(prsync__m0__g4[18]),
    .pin_s_rx_clk(prsync__m0__g2[0]),
    .pin_s_rx_crdtRB_free(prsync__m0__g2[1]),
    .pin_s_rx_flit_b0(prsync__m0__g2[2]),
    .pin_s_rx_flit_b1(prsync__m0__g2[3]),
    .pin_s_rx_flit_b10(prsync__m0__g2[4]),
    .pin_s_rx_flit_b11(prsync__m0__g2[5]),
    .pin_s_rx_flit_b12(prsync__m0__g2[6]),
    .pin_s_rx_flit_b13(prsync__m0__g2[7]),
    .pin_s_rx_flit_b14(prsync__m0__g2[8]),
    .pin_s_rx_flit_b15(prsync__m0__g2[9]),
    .pin_s_rx_flit_b2(prsync__m0__g2[10]),
    .pin_s_rx_flit_b3(prsync__m0__g2[11]),
    .pin_s_rx_flit_b4(prsync__m0__g2[12]),
    .pin_s_rx_flit_b5(prsync__m0__g2[13]),
    .pin_s_rx_flit_b6(prsync__m0__g2[14]),
    .pin_s_rx_flit_b7(prsync__m0__g2[15]),
    .pin_s_rx_flit_b8(prsync__m0__g2[16]),
    .pin_s_rx_flit_b9(prsync__m0__g2[17]),
    .pin_s_rx_rplyPkgID(prsync__m0__g2[19]),
    .pin_s_rx_vld(prsync__m0__g2[18]),
    .pin_s_tx_clk(prsync__m0__g1[0]),
    .pin_s_tx_crdtARW_free(prsync__m0__g1[1]),
    .pin_s_tx_flit_b0(prsync__m0__g1[2]),
    .pin_s_tx_flit_b1(prsync__m0__g1[3]),
    .pin_s_tx_flit_b2(prsync__m0__g1[4]),
    .pin_s_tx_flit_b3(prsync__m0__g1[5]),
    .pin_s_tx_flit_b4(prsync__m0__g1[6]),
    .pin_s_tx_flit_b5(prsync__m0__g1[7]),
    .pin_s_tx_flit_b6(prsync__m0__g1[8]),
    .pin_s_tx_flit_b7(prsync__m0__g1[9]),
    .pin_s_tx_flit_vld(prsync__m0__g1[10]),
    .pin_s_tx_rplyPkgID(prsync__m0__g1[11])
  );
  muyan muyan_10 (
  );
  muyan muyan_11 (
  );
  muyan muyan_12 (
  );
  muyan muyan_13 (
  );
  muyan muyan_14 (
  );
  muyan muyan_15 (
  );
  muyan muyan_2 (
  );
  muyan muyan_3 (
  );
  muyan muyan_4 (
  );
  muyan muyan_5 (
  );
  muyan muyan_6 (
  );
  muyan muyan_7 (
  );
  muyan muyan_8 (
  );
  muyan muyan_9 (
  );
  PRTOOL_INTERPOSER prtool_interposer (
    .xinzhai_jtag_tck(prunconnected__p0),
    .xinzhai_jtag_tdi(prunconnected__p1),
    .xinzhai_jtag_tdo(prsync__m0__g2[2]),
    .xinzhai_jtag_tms(prunconnected__p3),
    .xinzhai_jtag_trstn(prunconnected__p4),
    .xinzhai_muyan_0_POR(prunconnected__p5),
    .xinzhai_muyan_0_Test_mode(prunconnected__p6),
    .xinzhai_muyan_0_interrupt_0(prunconnected__p7),
    .xinzhai_muyan_0_interrupt_1(prunconnected__p8),
    .xinzhai_muyan_10_POR(prunconnected__p9),
    .xinzhai_muyan_10_Test_mode(prunconnected__p10),
    .xinzhai_muyan_10_interrupt_0(prunconnected__p11),
    .xinzhai_muyan_10_interrupt_1(prunconnected__p12),
    .xinzhai_muyan_11_POR(prunconnected__p13),
    .xinzhai_muyan_11_Test_mode(prunconnected__p14),
    .xinzhai_muyan_11_interrupt_0(prunconnected__p15),
    .xinzhai_muyan_11_interrupt_1(prunconnected__p16),
    .xinzhai_muyan_12_POR(prunconnected__p17),
    .xinzhai_muyan_12_Test_mode(prunconnected__p18),
    .xinzhai_muyan_12_interrupt_0(prunconnected__p19),
    .xinzhai_muyan_12_interrupt_1(prunconnected__p20),
    .xinzhai_muyan_13_POR(prunconnected__p21),
    .xinzhai_muyan_13_Test_mode(prunconnected__p22),
    .xinzhai_muyan_13_interrupt_0(prunconnected__p23),
    .xinzhai_muyan_13_interrupt_1(prunconnected__p24),
    .xinzhai_muyan_14_POR(prunconnected__p25),
    .xinzhai_muyan_14_Test_mode(prunconnected__p26),
    .xinzhai_muyan_14_interrupt_0(prunconnected__p27),
    .xinzhai_muyan_14_interrupt_1(prunconnected__p28),
    .xinzhai_muyan_15_POR(prunconnected__p29),
    .xinzhai_muyan_15_Test_mode(prunconnected__p30),
    .xinzhai_muyan_15_interrupt_0(prunconnected__p31),
    .xinzhai_muyan_15_interrupt_1(prunconnected__p32),
    .xinzhai_muyan_1_POR(prunconnected__p33),
    .xinzhai_muyan_1_Test_mode(prunconnected__p34),
    .xinzhai_muyan_1_interrupt_0(prunconnected__p35),
    .xinzhai_muyan_1_interrupt_1(prunconnected__p36),
    .xinzhai_muyan_2_POR(prunconnected__p37),
    .xinzhai_muyan_2_Test_mode(prunconnected__p38),
    .xinzhai_muyan_2_interrupt_0(prunconnected__p39),
    .xinzhai_muyan_2_interrupt_1(prunconnected__p40),
    .xinzhai_muyan_3_POR(prunconnected__p41),
    .xinzhai_muyan_3_Test_mode(prunconnected__p42),
    .xinzhai_muyan_3_interrupt_0(prunconnected__p43),
    .xinzhai_muyan_3_interrupt_1(prunconnected__p44),
    .xinzhai_muyan_4_POR(prunconnected__p45),
    .xinzhai_muyan_4_Test_mode(prunconnected__p46),
    .xinzhai_muyan_4_interrupt_0(prunconnected__p47),
    .xinzhai_muyan_4_interrupt_1(prunconnected__p48),
    .xinzhai_muyan_5_POR(prunconnected__p49),
    .xinzhai_muyan_5_Test_mode(prunconnected__p50),
    .xinzhai_muyan_5_interrupt_0(prunconnected__p51),
    .xinzhai_muyan_5_interrupt_1(prunconnected__p52),
    .xinzhai_muyan_6_POR(prunconnected__p53),
    .xinzhai_muyan_6_Test_mode(prunconnected__p54),
    .xinzhai_muyan_6_interrupt_0(prunconnected__p55),
    .xinzhai_muyan_6_interrupt_1(prunconnected__p56),
    .xinzhai_muyan_7_POR(prunconnected__p57),
    .xinzhai_muyan_7_Test_mode(prunconnected__p58),
    .xinzhai_muyan_7_interrupt_0(prunconnected__p59),
    .xinzhai_muyan_7_interrupt_1(prunconnected__p60),
    .xinzhai_muyan_8_POR(prunconnected__p61),
    .xinzhai_muyan_8_Test_mode(prunconnected__p62),
    .xinzhai_muyan_8_interrupt_0(prunconnected__p63),
    .xinzhai_muyan_8_interrupt_1(prunconnected__p64),
    .xinzhai_muyan_9_POR(prunconnected__p65),
    .xinzhai_muyan_9_Test_mode(prunconnected__p66),
    .xinzhai_muyan_9_interrupt_0(prunconnected__p67),
    .xinzhai_muyan_9_interrupt_1(prunconnected__p68),
    .xinzhai_spi_csn(prunconnected__p69),
    .xinzhai_spi_miso(prunconnected__p70),
    .xinzhai_spi_mosi(prunconnected__p71),
    .xinzhai_spi_s_csn_1(prunconnected__p72),
    .xinzhai_spi_s_csn_2(prunconnected__p73),
    .xinzhai_spi_s_din_1(prunconnected__p74),
    .xinzhai_spi_s_din_2(prunconnected__p75),
    .xinzhai_spi_s_dout_1(prunconnected__p76),
    .xinzhai_spi_s_dout_2(prunconnected__p77),
    .xinzhai_spi_s_sck_1(prunconnected__p78),
    .xinzhai_spi_s_sck_2(prunconnected__p79),
    .xinzhai_spi_sck(prunconnected__p80),
    .xinzhai_uart_rxd(prunconnected__p81),
    .xinzhai_uart_txd(prunconnected__p82)
  );
endmodule
